/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import business.BasketController;
import business.ProductController;
import core.Helper;
import entity.Basket;
import entity.Product;
import java.awt.Toolkit;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.SpinnerNumberModel;

public class BasketUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BasketUI.class.getName());

    private Product product;
    private ProductController productController;
    private Basket basket;
    private BasketController basketController;

    public BasketUI(Product product) {
        this.product = product;
        this.productController = new ProductController();
        this.basketController = new BasketController();
        this.basket = basketController.getByProductID(this.product.getId());

        initComponents();
        ((javax.swing.JSpinner.DefaultEditor) spnr_quantity.getEditor()).getTextField().setEditable(false);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.add(container);
        this.setTitle("Warenkorb");
        this.setSize(400, 450);
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width - this.getSize().width) / 2;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height - this.getSize().height) / 2;
        this.setLocation(x, y);
        this.setVisible(true);

        if (this.product.getId() == 0) {
            dispose();
            Helper.showMsg("dieses Produkt existiert nicht");
        } else {

            lbl_name.setText(this.product.getName());
            lbl_code.setText(this.product.getCode());
            lbl_price.setText(String.valueOf(this.product.getPrice()));
            lbl_stock.setText(String.valueOf(this.product.getStock()));
        }
        if (this.basket.getId() != 0) {
            this.setTitle("Warenkorb");
            lbl_basket_title.setText("Warenkorb bearbeiten");
            spnr_quantity.setValue(this.basket.getQuantity());
        } else {
            this.basket.setProduct_id(this.product.getId());
            lbl_basket_title.setText("In den Warenkorb");
            spnr_quantity.setValue(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        lbl_basket_title = new javax.swing.JLabel();
        lbl_product_name = new javax.swing.JLabel();
        lbl_product_code = new javax.swing.JLabel();
        lbl_product_price = new javax.swing.JLabel();
        lbl_product_stock = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_code = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        lbl_stock = new javax.swing.JLabel();
        lbl_quantity = new javax.swing.JLabel();
        spnr_quantity = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,this.product.getStock(),1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        container.setPreferredSize(new java.awt.Dimension(300, 521));

        lbl_basket_title.setText("Product");

        lbl_product_name.setText("Productname");

        lbl_product_code.setText("Productnummer");

        lbl_product_price.setText("Stück Preis");

        lbl_product_stock.setText("Lagerstatus");

        btn_save.setText("Speichern");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        lbl_name.setText("name");

        lbl_code.setText("nummer");

        lbl_price.setText("preis");

        lbl_stock.setText("Stück");

        lbl_quantity.setText("Stück");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_basket_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(lbl_product_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_product_code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_product_price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spnr_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_product_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(lbl_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_basket_title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_price, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_product_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_quantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnr_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_product_stock, lbl_quantity});

        getContentPane().add(container);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        this.basket.setQuantity((int) spnr_quantity.getValue());
        //System.out.println(this.basket.toString());
        if (this.basket.getId() != 0) {
            if ((int) spnr_quantity.getValue() == 0) {
                if (this.basketController.delete(this.basket.getId())) {
                    Helper.showMsg(this.basket.getProduct().getName() + " wurde entfernt");
                } else {
                    Helper.showMsg("error");
                }
            }
            if (this.basketController.update(this.basket)) {
                Helper.showMsg("done");
            }
        } else if ((int) spnr_quantity.getValue() > 0) {
            if (this.basketController.save(this.basket)) {
                Helper.showMsg("done");
            } else {
                Helper.showMsg("error");
            }
        }
        dispose();
        /*boolean result = false;
        this.product.setName(fld_product_name.getText());
        this.product.setCode(fld_product_code.getText());
        this.product.setPrice(Integer.parseInt(fld_product_price.getText()));
        this.product.setStock(Integer.parseInt(fld_product_stock.getText()));
        if (product.getId() == 0) {
            result = productController.save(this.product);
        } else {
            result = productController.update(this.product);
        }
        if (result) {
            Helper.showMsg("done");
            dispose();
        } else {
            Helper.showMsg("error");
        }*/
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new BasketUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JPanel container;
    private javax.swing.JLabel lbl_basket_title;
    private javax.swing.JLabel lbl_code;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_product_code;
    private javax.swing.JLabel lbl_product_name;
    private javax.swing.JLabel lbl_product_price;
    private javax.swing.JLabel lbl_product_stock;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JSpinner spnr_quantity;
    // End of variables declaration//GEN-END:variables
}
