package view;

import business.BasketController;
import business.CartController;
import business.CustomerController;
import business.ProductController;
import core.Helper;
import core.Item;
import entity.Basket;
import entity.Cart;
import entity.Customer;
import entity.Product;
import entity.User;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class DashboardUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardUI.class.getName());

    private User user;

    private CustomerController customerController;
    private DefaultTableModel tmdl_customer = new DefaultTableModel();
    private JPopupMenu popup_customer = new JPopupMenu();

    private ProductController productController;
    private DefaultTableModel tmdl_product = new DefaultTableModel();
    private JPopupMenu popup_product = new JPopupMenu();

    private BasketController basketController;
    private DefaultTableModel tmdl_basket = new DefaultTableModel();
    private JPopupMenu popup_basket = new JPopupMenu();

    private CartController cartController;
    private DefaultTableModel tmdl_cart = new DefaultTableModel();

    public DashboardUI(User user) {
        this.user = user;
        this.customerController = new CustomerController();
        initComponents();
        if (user == null) {
            Helper.showMsg("error");
            dispose();
        }
        this.add(container);
        this.setTitle("Kundenmanagementsystem");
        //this.setSize(1366, 768); 
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width - this.getSize().width) / 2;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height - this.getSize().height) / 2;
        this.setLocation(x, y);
        this.setVisible(true);
        lbl_welcome.setText(lbl_welcome.getText() + " " + user.getName().toString());

        //System.out.println(customerController.findAll());
        this.cmb_f_customer_type.setSelectedItem(null);
        loadCustomerTabel(null);
        loadCustomerPopupMenu();

        // PRODUCT TAB
        this.productController = new ProductController();
        cmb_fltr_product_stock.setSelectedItem(null);
        loadProductTabel(null);
        loadProductPopupMenu();

        //Basket
        this.basketController = new BasketController();
        loadBasketTabel();
        loadBasketCustomerCombo();
        loadBasketPopupMenu();

        this.cartController = new CartController();
        loadCartTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        pnl_top = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        tab_menu = new javax.swing.JTabbedPane();
        pnl_customer = new javax.swing.JPanel();
        scrl_customer = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();
        pnl_customer_filter = new javax.swing.JPanel();
        lbl_fltr_cstmr_name = new javax.swing.JLabel();
        lbl_fltr_cstmr_type = new javax.swing.JLabel();
        cmb_f_customer_type = new javax.swing.JComboBox<>();
        fld_f_customer_name = new javax.swing.JTextField();
        btn_customer_filter = new javax.swing.JButton();
        btn_customer_reset = new javax.swing.JButton();
        btn_customer_new = new javax.swing.JButton();
        pnl_products = new javax.swing.JPanel();
        scrl_products = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();
        pnd_product_filter = new javax.swing.JPanel();
        pnl_product_filter = new javax.swing.JPanel();
        pnl_product_btns = new javax.swing.JPanel();
        btn_product_filter = new javax.swing.JButton();
        btn_product_reset = new javax.swing.JButton();
        btn_product_new = new javax.swing.JButton();
        pnl_product_flds_and_cmb = new javax.swing.JPanel();
        lbl_fltr_product_name = new javax.swing.JLabel();
        lbl_fltr_product_code = new javax.swing.JLabel();
        lbl_fltr_product_stock = new javax.swing.JLabel();
        fld_fltr_product_name = new javax.swing.JTextField();
        fld_fltr_product_code = new javax.swing.JTextField();
        cmb_fltr_product_stock = new javax.swing.JComboBox<>();
        pnl_basket = new javax.swing.JPanel();
        scrl_basket = new javax.swing.JScrollPane();
        tbl_basket = new javax.swing.JTable();
        pnl_basket_filter = new javax.swing.JPanel();
        pnl_basket_filter_in = new javax.swing.JPanel();
        pnl_basket_btns = new javax.swing.JPanel();
        btn_basket_reset = new javax.swing.JButton();
        btn_basket_new = new javax.swing.JButton();
        pnl_basket_lbls_and_cmb = new javax.swing.JPanel();
        lbl_basket_cost_title = new javax.swing.JLabel();
        lbl_basket_product_count_title = new javax.swing.JLabel();
        cmb_fltr_basket_customer = new javax.swing.JComboBox<>();
        lbl_fltr_basket_customer = new javax.swing.JLabel();
        lbl_basket_cost = new javax.swing.JLabel();
        lbl_basket_product_count = new javax.swing.JLabel();
        pnl_cart = new javax.swing.JPanel();
        scrl_cart = new javax.swing.JScrollPane();
        tbl_cart = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 750));
        setPreferredSize(new java.awt.Dimension(1150, 750));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        container.setMinimumSize(new java.awt.Dimension(1100, 700));
        container.setPreferredSize(new java.awt.Dimension(1100, 700));

        lbl_welcome.setText("Willkommen");

        btn_logout.setText("Abmelden");
        btn_logout.addActionListener(this::btn_logoutActionPerformed);

        javax.swing.GroupLayout pnl_topLayout = new javax.swing.GroupLayout(pnl_top);
        pnl_top.setLayout(pnl_topLayout);
        pnl_topLayout.setHorizontalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addContainerGap())
        );
        pnl_topLayout.setVerticalGroup(
            pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_welcome)
                    .addComponent(btn_logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_topLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_logout, lbl_welcome});

        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrl_customer.setViewportView(tbl_customer);

        lbl_fltr_cstmr_name.setText("Kundenname");

        lbl_fltr_cstmr_type.setText("Kundentyp");

        cmb_f_customer_type.setModel( new javax.swing.DefaultComboBoxModel<>(Customer.TYPE.values()));

        btn_customer_filter.setText("Suchen");
        btn_customer_filter.addActionListener(this::btn_customer_filterActionPerformed);

        btn_customer_reset.setText("Löschen");
        btn_customer_reset.addActionListener(this::btn_customer_resetActionPerformed);

        btn_customer_new.setText("Neu hinzufügen");
        btn_customer_new.addActionListener(this::btn_customer_newActionPerformed);

        javax.swing.GroupLayout pnl_customer_filterLayout = new javax.swing.GroupLayout(pnl_customer_filter);
        pnl_customer_filter.setLayout(pnl_customer_filterLayout);
        pnl_customer_filterLayout.setHorizontalGroup(
            pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_customer_filterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_customer_filterLayout.createSequentialGroup()
                        .addComponent(btn_customer_filter, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_customer_reset, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_customer_new, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(pnl_customer_filterLayout.createSequentialGroup()
                        .addGroup(pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_f_customer_name)
                            .addComponent(lbl_fltr_cstmr_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fltr_cstmr_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_f_customer_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)))
                .addGap(6, 6, 6))
        );
        pnl_customer_filterLayout.setVerticalGroup(
            pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_customer_filterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fltr_cstmr_name)
                    .addComponent(lbl_fltr_cstmr_type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_f_customer_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_f_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_customer_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_customer_filter)
                    .addComponent(btn_customer_reset)
                    .addComponent(btn_customer_new))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_customerLayout = new javax.swing.GroupLayout(pnl_customer);
        pnl_customer.setLayout(pnl_customerLayout);
        pnl_customerLayout.setHorizontalGroup(
            pnl_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_customerLayout.createSequentialGroup()
                .addComponent(pnl_customer_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(611, 611, 611))
            .addComponent(scrl_customer)
        );
        pnl_customerLayout.setVerticalGroup(
            pnl_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_customer_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrl_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_menu.addTab("Kunde", pnl_customer);

        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrl_products.setViewportView(tbl_products);

        btn_product_filter.setText("Suchen");
        btn_product_filter.addActionListener(this::btn_product_filterActionPerformed);

        btn_product_reset.setText("Löschen");
        btn_product_reset.addActionListener(this::btn_product_resetActionPerformed);

        btn_product_new.setText("Neu hinzufügen");
        btn_product_new.addActionListener(this::btn_product_newActionPerformed);

        javax.swing.GroupLayout pnl_product_btnsLayout = new javax.swing.GroupLayout(pnl_product_btns);
        pnl_product_btns.setLayout(pnl_product_btnsLayout);
        pnl_product_btnsLayout.setHorizontalGroup(
            pnl_product_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_product_btnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_product_filter, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_product_reset, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_product_new, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );
        pnl_product_btnsLayout.setVerticalGroup(
            pnl_product_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_product_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_product_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_product_new, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbl_fltr_product_name.setText("Produktname");

        lbl_fltr_product_code.setText("Productnummer");

        lbl_fltr_product_stock.setText("Lagerstatus");

        fld_fltr_product_name.addActionListener(this::fld_fltr_product_nameActionPerformed);

        cmb_fltr_product_stock.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { null,"Vorrärig", "Ausverkauft"}));

        javax.swing.GroupLayout pnl_product_flds_and_cmbLayout = new javax.swing.GroupLayout(pnl_product_flds_and_cmb);
        pnl_product_flds_and_cmb.setLayout(pnl_product_flds_and_cmbLayout);
        pnl_product_flds_and_cmbLayout.setHorizontalGroup(
            pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_product_flds_and_cmbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fltr_product_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_fltr_product_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fld_fltr_product_code)
                    .addComponent(lbl_fltr_product_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_fltr_product_stock, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fltr_product_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_product_flds_and_cmbLayout.setVerticalGroup(
            pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_product_flds_and_cmbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fltr_product_code)
                    .addComponent(lbl_fltr_product_stock)
                    .addComponent(lbl_fltr_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_product_flds_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fld_fltr_product_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fld_fltr_product_code, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_fltr_product_stock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnl_product_flds_and_cmbLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_fltr_product_code, lbl_fltr_product_name, lbl_fltr_product_stock});

        javax.swing.GroupLayout pnl_product_filterLayout = new javax.swing.GroupLayout(pnl_product_filter);
        pnl_product_filter.setLayout(pnl_product_filterLayout);
        pnl_product_filterLayout.setHorizontalGroup(
            pnl_product_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_product_flds_and_cmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_product_filterLayout.createSequentialGroup()
                .addComponent(pnl_product_btns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(271, 271, 271))
        );
        pnl_product_filterLayout.setVerticalGroup(
            pnl_product_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_product_filterLayout.createSequentialGroup()
                .addComponent(pnl_product_flds_and_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_product_btns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnd_product_filterLayout = new javax.swing.GroupLayout(pnd_product_filter);
        pnd_product_filter.setLayout(pnd_product_filterLayout);
        pnd_product_filterLayout.setHorizontalGroup(
            pnd_product_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnd_product_filterLayout.createSequentialGroup()
                .addComponent(pnl_product_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(274, 274, 274))
        );
        pnd_product_filterLayout.setVerticalGroup(
            pnd_product_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnd_product_filterLayout.createSequentialGroup()
                .addComponent(pnl_product_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_productsLayout = new javax.swing.GroupLayout(pnl_products);
        pnl_products.setLayout(pnl_productsLayout);
        pnl_productsLayout.setHorizontalGroup(
            pnl_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(pnd_product_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrl_products))
        );
        pnl_productsLayout.setVerticalGroup(
            pnl_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_productsLayout.createSequentialGroup()
                .addComponent(pnd_product_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrl_products, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_menu.addTab("Produkte", pnl_products);

        tbl_basket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrl_basket.setViewportView(tbl_basket);

        btn_basket_reset.setText("Liste löschen");
        btn_basket_reset.addActionListener(this::btn_basket_resetActionPerformed);

        btn_basket_new.setText("Bestellung erstellen");
        btn_basket_new.addActionListener(this::btn_basket_newActionPerformed);

        javax.swing.GroupLayout pnl_basket_btnsLayout = new javax.swing.GroupLayout(pnl_basket_btns);
        pnl_basket_btns.setLayout(pnl_basket_btnsLayout);
        pnl_basket_btnsLayout.setHorizontalGroup(
            pnl_basket_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_basket_btnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_basket_reset, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_basket_new, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_basket_btnsLayout.setVerticalGroup(
            pnl_basket_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_basket_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_basket_new, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lbl_basket_cost_title.setText("Gesamtkosten");

        lbl_basket_product_count_title.setText("Anzahl der Produkte");

        cmb_fltr_basket_customer.setMaximumSize(new java.awt.Dimension(32767, 26));

        lbl_fltr_basket_customer.setText("Kunde auswählen");

        lbl_basket_cost.setText("0€");

        lbl_basket_product_count.setText("0");

        javax.swing.GroupLayout pnl_basket_lbls_and_cmbLayout = new javax.swing.GroupLayout(pnl_basket_lbls_and_cmb);
        pnl_basket_lbls_and_cmb.setLayout(pnl_basket_lbls_and_cmbLayout);
        pnl_basket_lbls_and_cmbLayout.setHorizontalGroup(
            pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_basket_lbls_and_cmbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fltr_basket_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(cmb_fltr_basket_customer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_basket_cost_title, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(lbl_basket_cost, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_basket_product_count_title, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(lbl_basket_product_count, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_basket_lbls_and_cmbLayout.setVerticalGroup(
            pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_basket_lbls_and_cmbLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_fltr_basket_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_basket_cost)
                        .addComponent(lbl_basket_product_count))
                    .addGroup(pnl_basket_lbls_and_cmbLayout.createSequentialGroup()
                        .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_basket_lbls_and_cmbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_basket_cost_title, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                .addComponent(lbl_fltr_basket_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_basket_product_count_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addContainerGap())
        );

        pnl_basket_lbls_and_cmbLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmb_fltr_basket_customer, lbl_basket_cost, lbl_basket_product_count});

        pnl_basket_lbls_and_cmbLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_basket_cost_title, lbl_basket_product_count_title, lbl_fltr_basket_customer});

        javax.swing.GroupLayout pnl_basket_filter_inLayout = new javax.swing.GroupLayout(pnl_basket_filter_in);
        pnl_basket_filter_in.setLayout(pnl_basket_filter_inLayout);
        pnl_basket_filter_inLayout.setHorizontalGroup(
            pnl_basket_filter_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_basket_lbls_and_cmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_basket_filter_inLayout.createSequentialGroup()
                .addComponent(pnl_basket_btns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275))
        );
        pnl_basket_filter_inLayout.setVerticalGroup(
            pnl_basket_filter_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_basket_filter_inLayout.createSequentialGroup()
                .addComponent(pnl_basket_lbls_and_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_basket_btns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_basket_filterLayout = new javax.swing.GroupLayout(pnl_basket_filter);
        pnl_basket_filter.setLayout(pnl_basket_filterLayout);
        pnl_basket_filterLayout.setHorizontalGroup(
            pnl_basket_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_basket_filterLayout.createSequentialGroup()
                .addComponent(pnl_basket_filter_in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(274, 274, 274))
        );
        pnl_basket_filterLayout.setVerticalGroup(
            pnl_basket_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_basket_filterLayout.createSequentialGroup()
                .addComponent(pnl_basket_filter_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_basketLayout = new javax.swing.GroupLayout(pnl_basket);
        pnl_basket.setLayout(pnl_basketLayout);
        pnl_basketLayout.setHorizontalGroup(
            pnl_basketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_basketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(pnl_basket_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrl_basket, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE))
        );
        pnl_basketLayout.setVerticalGroup(
            pnl_basketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_basketLayout.createSequentialGroup()
                .addComponent(pnl_basket_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrl_basket, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab_menu.addTab("Bestellung erstellen", pnl_basket);

        tbl_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrl_cart.setViewportView(tbl_cart);

        javax.swing.GroupLayout pnl_cartLayout = new javax.swing.GroupLayout(pnl_cart);
        pnl_cart.setLayout(pnl_cartLayout);
        pnl_cartLayout.setHorizontalGroup(
            pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrl_cart, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
        );
        pnl_cartLayout.setVerticalGroup(
            pnl_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrl_cart, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        tab_menu.addTab("Bestellungen", pnl_cart);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tab_menu)
                    .addComponent(pnl_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_menu)
                .addContainerGap())
        );

        getContentPane().add(container);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        dispose();
        LoginUI loginUI = new LoginUI();

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_customer_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_filterActionPerformed
        loadCustomerTabel(null);
        ArrayList<Customer> filteredCustomer = this.customerController.filter(
                this.fld_f_customer_name.getText(),
                (Customer.TYPE) this.cmb_f_customer_type.getSelectedItem()
        );
        loadCustomerTabel(filteredCustomer);
    }//GEN-LAST:event_btn_customer_filterActionPerformed

    private void btn_customer_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_newActionPerformed
        CustomerUI customerUI = new CustomerUI(new Customer());
        customerUI.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadCustomerTabel(null);
                loadBasketCustomerCombo();
            }
        });
    }//GEN-LAST:event_btn_customer_newActionPerformed

    private void btn_customer_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customer_resetActionPerformed
        this.cmb_f_customer_type.setSelectedItem(null);
        this.fld_f_customer_name.setText(null);
        loadCustomerTabel(null);
    }//GEN-LAST:event_btn_customer_resetActionPerformed

    private void fld_fltr_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_fltr_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_fltr_product_nameActionPerformed

    private void btn_product_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_product_newActionPerformed
        ProductUI productUI = new ProductUI(new Product());
        productUI.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadProductTabel(null);
            }
        });
    }//GEN-LAST:event_btn_product_newActionPerformed

    private void btn_product_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_product_resetActionPerformed
        fld_fltr_product_name.setText(null);
        fld_fltr_product_code.setText(null);
        cmb_fltr_product_stock.setSelectedItem(null);
        loadProductTabel(null);
    }//GEN-LAST:event_btn_product_resetActionPerformed

    private void btn_product_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_product_filterActionPerformed
        ArrayList<Product> filteredProduct = this.productController.filter(
                this.fld_fltr_product_name.getText(),
                this.fld_fltr_product_code.getText(),
                this.cmb_fltr_product_stock.getSelectedIndex()
        );
        loadProductTabel(filteredProduct);
    }//GEN-LAST:event_btn_product_filterActionPerformed

    private void btn_basket_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_basket_resetActionPerformed
        if (basketController.clear()) {
            loadBasketTabel();
            Helper.showMsg("done");
        } else {
            Helper.showMsg("error");
        }
    }//GEN-LAST:event_btn_basket_resetActionPerformed

    private void btn_basket_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_basket_newActionPerformed
        if (cmb_fltr_basket_customer.getSelectedIndex() != -1) {
            System.out.println(cmb_fltr_basket_customer.getSelectedIndex());
            int selectedCustomerID = cmb_fltr_basket_customer.getItemAt(cmb_fltr_basket_customer.getSelectedIndex()).getKey();
            //^^this.cmb_fltr_basket_customer.addItem(new Item(comboKey, comboValue));^^
            Customer customer = this.customerController.getById(selectedCustomerID);
            if (customer.getId() != 0) {
                CartUI cartUI = new CartUI(this.customerController.getById(selectedCustomerID));
                cartUI.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        loadBasketTabel();
                        loadProductTabel(null);
                        loadCartTabel();
                    }
                });
            } else {
                Helper.showMsg("Kunde nicht gefunden");
            }
        } else {
            Helper.showMsg("Bitte wählen Sie einen gültigen Kunden aus");
        }

    }//GEN-LAST:event_btn_basket_newActionPerformed

    private void loadCustomerPopupMenu() {
        this.tbl_customer.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int selectedRow = tbl_customer.rowAtPoint(e.getPoint());
                //System.out.println(selectedRow);
                tbl_customer.setRowSelectionInterval(selectedRow, selectedRow);
            }
        });

        this.popup_customer.add("Bearbeiten").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_customer.getValueAt(tbl_customer.getSelectedRow(), 0).toString());
            System.out.println("Bearbeiten ID:" + selectId);
            CustomerUI customerUI = new CustomerUI(this.customerController.getById(selectId));
            customerUI.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    loadCustomerTabel(null);
                    loadBasketCustomerCombo();
                }
            });
        });
        this.popup_customer.add("Entfernen").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_customer.getValueAt(tbl_customer.getSelectedRow(), 0).toString());
            System.out.println("Entfernen ID:" + selectId);
            if (Helper.confirm("sure")) {
                if (this.customerController.delete(selectId)) {
                    loadCustomerTabel(null);
                    loadBasketCustomerCombo();
                    Helper.showMsg("done");
                } else {
                    Helper.showMsg("error");
                }
            }
        });

        this.tbl_customer.setComponentPopupMenu(this.popup_customer);
    }

    private void loadCustomerTabel(ArrayList<Customer> customers) {
        Object[] columnCustomer = {"ID", "Kundenname", "Typ", "Telefonnummer", "Email", "Adresse"};

        if (customers == null) {
            customers = this.customerController.findAll();
        }

        // Table Cleared
        DefaultTableModel clearModel = (DefaultTableModel) this.tbl_customer.getModel();
        clearModel.setRowCount(0);

        this.tmdl_customer.setColumnIdentifiers(columnCustomer);
        for (Customer customer : customers) {
            Object[] rowObject = {
                customer.getId(),
                customer.getName(),
                customer.getType(),
                customer.getPhone(),
                customer.getEmail(),
                customer.getAddress(),};
            this.tmdl_customer.addRow(rowObject);
        }
        this.tbl_customer.setModel(tmdl_customer);
        this.tbl_customer.getTableHeader().setReorderingAllowed(false);
        this.tbl_customer.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tbl_customer.setEnabled(true);
        this.tbl_customer.setDefaultEditor(Object.class, null);

        SwingUtilities.invokeLater(() -> {
            tbl_customer.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        });

    }

    private void loadProductTabel(ArrayList<Product> products) {
        Object[] columnProduct = {"ID", "Productname", "Productnummer", "Preis", "Lagerstatus"};

        if (products == null) {
            products = this.productController.findAll();
        }

        // Table Cleared
        DefaultTableModel clearModel = (DefaultTableModel) this.tbl_products.getModel();
        clearModel.setRowCount(0);

        this.tmdl_product.setColumnIdentifiers(columnProduct);
        for (Product product : products) {
            Object[] rowObject = {
                product.getId(),
                product.getName(),
                product.getCode(),
                product.getPrice(),
                product.getStock(),};
            this.tmdl_product.addRow(rowObject);
        }
        this.tbl_products.setModel(tmdl_product);
        this.tbl_products.getTableHeader().setReorderingAllowed(false);
        this.tbl_products.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tbl_products.setEnabled(true);
        this.tbl_products.setDefaultEditor(Object.class, null);

        SwingUtilities.invokeLater(() -> {
            tbl_products.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        });
    }

    private void loadProductPopupMenu() {
        this.tbl_products.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int selectedRow = tbl_products.rowAtPoint(e.getPoint());
                //System.out.println(selectedRow);
                tbl_products.setRowSelectionInterval(selectedRow, selectedRow);
            }
        });

        this.popup_product.add("In den Warenkorb").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_products.getValueAt(tbl_products.getSelectedRow(), 0).toString());
            System.out.println("In den Warenkorb ID:" + selectId);
            Product basketProduct = productController.getById(selectId);
            if (basketProduct.getStock() <= 0) {
                Helper.showMsg("Produkt nicht vorrätig!");
            } else {
                BasketUI basketUI = new BasketUI(basketProduct);
                basketUI.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        loadBasketTabel();
                    }
                });
            }
        });

        this.popup_product.add("Bearbeiten").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_products.getValueAt(tbl_products.getSelectedRow(), 0).toString());
            //System.out.println("Bearbeiten ID:" + selectId);
            ProductUI productUI = new ProductUI(this.productController.getById(selectId));
            productUI.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    loadProductTabel(null);
                    loadBasketTabel();
                }
            });
        });
        this.popup_product.add("Entfernen").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_products.getValueAt(tbl_products.getSelectedRow(), 0).toString());
            //System.out.println("Entfernen ID:" + selectId);
            if (Helper.confirm("sure")) {
                if (this.productController.delete(selectId)) {
                    loadProductTabel(null);
                    loadBasketTabel();
                    Helper.showMsg("done");
                } else {
                    Helper.showMsg("error");
                }
            }
        });

        this.tbl_products.setComponentPopupMenu(this.popup_product);
    }

    private void loadBasketTabel() {
        Object[] columnBasket = {"ID", "Productname", "Productnummer", "Lagerstatus", "Preis", "Stück", "Gesamtpreis"};
        ArrayList<Basket> baskets = this.basketController.findAll();

        // Table Cleared
        DefaultTableModel clearModel = (DefaultTableModel) this.tbl_basket.getModel();
        clearModel.setRowCount(0);

        this.tmdl_basket.setColumnIdentifiers(columnBasket);
        int totalBasketPrice = 0, productCount=0;
        for (Basket basket : baskets) {
            Object[] rowObject = {
                basket.getId(),
                basket.getProduct().getName(),
                basket.getProduct().getCode(),
                basket.getProduct().getStock(),
                basket.getProduct().getPrice(),
                basket.getQuantity(),
                basket.getQuantity() * basket.getProduct().getPrice(),};
            this.tmdl_basket.addRow(rowObject);
            
            productCount += basket.getQuantity();
            totalBasketPrice += basket.getQuantity() * basket.getProduct().getPrice();
        }
        this.lbl_basket_cost.setText(String.valueOf(totalBasketPrice) + "€");
        this.lbl_basket_product_count.setText(String.valueOf(productCount) + " Stück");

        this.tbl_basket.setModel(tmdl_basket);
        this.tbl_basket.getTableHeader().setReorderingAllowed(false);
        this.tbl_basket.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tbl_basket.setEnabled(true);
        this.tbl_basket.setDefaultEditor(Object.class, null);

        SwingUtilities.invokeLater(() -> {
            tbl_basket.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        });
    }

    private void loadBasketCustomerCombo() {

        ArrayList<Customer> customers = this.customerController.findAll();
        this.cmb_fltr_basket_customer.removeAllItems();
        for (Customer customer : customers) {
            int comboKey = customer.getId();
            String comboValue = customer.getName();
            this.cmb_fltr_basket_customer.addItem(new Item(comboKey, comboValue));
        }
        this.cmb_fltr_basket_customer.setSelectedItem(null);
    }

    private void loadCartTabel() {
        Object[] columnCart = {"ID", "Kundenname", "Productname", "Preis", "Stück", "Gesamtpreis", "Bestelldatum", "Hinweis"};
        ArrayList<Cart> carts = this.cartController.findAll();

        // Table Cleared
        DefaultTableModel clearModel = (DefaultTableModel) this.tbl_cart.getModel();
        clearModel.setRowCount(0);

        this.tmdl_cart.setColumnIdentifiers(columnCart);
        for (Cart cart : carts) {
            Object[] rowObject = {
                cart.getId(),
                cart.getCustomer().getName(),
                cart.getProduct().getName(),
                cart.getPrice(),
                cart.getQuantity(),
                cart.getPrice()*cart.getQuantity(),
                cart.getDate(),
                cart.getNote()
            };
            this.tmdl_cart.addRow(rowObject);

        }

        this.tbl_cart.setModel(tmdl_cart);
        this.tbl_cart.getTableHeader().setReorderingAllowed(false);
        this.tbl_cart.getColumnModel().getColumn(0).setMaxWidth(50);
        this.tbl_cart.setEnabled(true);
        this.tbl_cart.setDefaultEditor(Object.class, null);

        SwingUtilities.invokeLater(() -> {
            tbl_cart.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        });
    }

    private void loadBasketPopupMenu() {
        this.tbl_basket.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int selectedRow = tbl_basket.rowAtPoint(e.getPoint());
                //System.out.println(selectedRow);
                tbl_basket.setRowSelectionInterval(selectedRow, selectedRow);
            }
        });

        this.popup_basket.add("Bearbeiten").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_basket.getValueAt(tbl_basket.getSelectedRow(), 0).toString());
            System.out.println("Bearbeiten ID:" + selectId);
            Product basketProduct = basketController.getByID(selectId).getProduct();

            BasketUI basketUI = new BasketUI(basketProduct);
            basketUI.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    loadBasketTabel();
                }
            });

        });
        this.popup_basket.add("Entfernen").addActionListener(e -> {
            int selectId = Integer.parseInt(tbl_basket.getValueAt(tbl_basket.getSelectedRow(), 0).toString());
            //System.out.println("Entfernen ID:" + selectId);
            if (Helper.confirm("sure")) {
                if (this.basketController.delete(selectId)) {
                    loadBasketTabel();
                    Helper.showMsg("done");
                } else {
                    Helper.showMsg("error");
                }
            }
        });

        this.tbl_basket.setComponentPopupMenu(this.popup_basket);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_basket_new;
    private javax.swing.JButton btn_basket_reset;
    private javax.swing.JButton btn_customer_filter;
    private javax.swing.JButton btn_customer_new;
    private javax.swing.JButton btn_customer_reset;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_product_filter;
    private javax.swing.JButton btn_product_new;
    private javax.swing.JButton btn_product_reset;
    private javax.swing.JComboBox<Customer.TYPE> cmb_f_customer_type;
    private javax.swing.JComboBox<Item> cmb_fltr_basket_customer;
    private javax.swing.JComboBox<String> cmb_fltr_product_stock;
    private javax.swing.JPanel container;
    private javax.swing.JTextField fld_f_customer_name;
    private javax.swing.JTextField fld_fltr_product_code;
    private javax.swing.JTextField fld_fltr_product_name;
    private javax.swing.JLabel lbl_basket_cost;
    private javax.swing.JLabel lbl_basket_cost_title;
    private javax.swing.JLabel lbl_basket_product_count;
    private javax.swing.JLabel lbl_basket_product_count_title;
    private javax.swing.JLabel lbl_fltr_basket_customer;
    private javax.swing.JLabel lbl_fltr_cstmr_name;
    private javax.swing.JLabel lbl_fltr_cstmr_type;
    private javax.swing.JLabel lbl_fltr_product_code;
    private javax.swing.JLabel lbl_fltr_product_name;
    private javax.swing.JLabel lbl_fltr_product_stock;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel pnd_product_filter;
    private javax.swing.JPanel pnl_basket;
    private javax.swing.JPanel pnl_basket_btns;
    private javax.swing.JPanel pnl_basket_filter;
    private javax.swing.JPanel pnl_basket_filter_in;
    private javax.swing.JPanel pnl_basket_lbls_and_cmb;
    private javax.swing.JPanel pnl_cart;
    private javax.swing.JPanel pnl_customer;
    private javax.swing.JPanel pnl_customer_filter;
    private javax.swing.JPanel pnl_product_btns;
    private javax.swing.JPanel pnl_product_filter;
    private javax.swing.JPanel pnl_product_flds_and_cmb;
    private javax.swing.JPanel pnl_products;
    private javax.swing.JPanel pnl_top;
    private javax.swing.JScrollPane scrl_basket;
    private javax.swing.JScrollPane scrl_cart;
    private javax.swing.JScrollPane scrl_customer;
    private javax.swing.JScrollPane scrl_products;
    private javax.swing.JTabbedPane tab_menu;
    private javax.swing.JTable tbl_basket;
    private javax.swing.JTable tbl_cart;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTable tbl_products;
    // End of variables declaration//GEN-END:variables

}
