package view;

import business.ProductController;
import core.Helper;
import entity.Product;
import java.awt.Toolkit;

public class ProductUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductUI.class.getName());

    private Product product;
    private ProductController productController;

    public ProductUI(Product product) {
        this.product = product;
        this.productController = new ProductController();

        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.add(container);
        this.setTitle("Kunde hinzufügen");
        this.setSize(400, 450);
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width - this.getSize().width) / 2;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height - this.getSize().height) / 2;
        this.setLocation(x, y);
        this.setVisible(true);

        if (this.product.getId() != 0) {
            lbl_product_title.setText("Product Bearbeiten");
            fld_product_name.setText(this.product.getName());
            fld_product_code.setText(this.product.getCode());
            fld_product_price.setText(String.valueOf(this.product.getPrice()));
            fld_product_stock.setText(String.valueOf(this.product.getStock()));
        } else {
            lbl_product_title.setText("Product Hinzufügen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        lbl_product_title = new javax.swing.JLabel();
        lbl_product_name = new javax.swing.JLabel();
        fld_product_name = new javax.swing.JTextField();
        lbl_product_code = new javax.swing.JLabel();
        fld_product_code = new javax.swing.JTextField();
        lbl_product_price = new javax.swing.JLabel();
        fld_product_price = new javax.swing.JTextField();
        lbl_product_stock = new javax.swing.JLabel();
        fld_product_stock = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        container.setPreferredSize(new java.awt.Dimension(300, 521));

        lbl_product_title.setText("Product");

        lbl_product_name.setText("Productname");

        fld_product_name.addActionListener(this::fld_product_nameActionPerformed);

        lbl_product_code.setText("Productnummer");

        fld_product_code.addActionListener(this::fld_product_codeActionPerformed);

        lbl_product_price.setText("Preis");

        lbl_product_stock.setText("Lagerstatus");

        btn_save.setText("Speichern");
        btn_save.addActionListener(this::btn_saveActionPerformed);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_product_title, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(lbl_product_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_product_name)
                    .addComponent(lbl_product_code, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_product_code)
                    .addComponent(lbl_product_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_product_price)
                    .addComponent(lbl_product_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fld_product_stock))
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_product_title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_price, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_product_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_product_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fld_product_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(container);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_product_nameActionPerformed

    private void fld_product_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_product_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_product_codeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        boolean result = false;
        this.product.setName(fld_product_name.getText());
        this.product.setCode(fld_product_code.getText());
        this.product.setPrice(Integer.parseInt(fld_product_price.getText()));
        this.product.setStock(Integer.parseInt(fld_product_stock.getText()));
        if (product.getId() == 0) {
            result = productController.save(this.product);
        } else {
            result = productController.update(this.product);
        }
        if (result) {
            Helper.showMsg("done");
            dispose();
        } else {
            Helper.showMsg("error");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new ProductUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JPanel container;
    private javax.swing.JTextField fld_product_code;
    private javax.swing.JTextField fld_product_name;
    private javax.swing.JTextField fld_product_price;
    private javax.swing.JTextField fld_product_stock;
    private javax.swing.JLabel lbl_product_code;
    private javax.swing.JLabel lbl_product_name;
    private javax.swing.JLabel lbl_product_price;
    private javax.swing.JLabel lbl_product_stock;
    private javax.swing.JLabel lbl_product_title;
    // End of variables declaration//GEN-END:variables
}
